### ISSUE TITLE
Bottom bar bouncing

### ISSUE THREAD

**Issue by b4rtt** [rhanb/nativescript-bottombar#51]
Hi I found a little problem. It's not a very big problem but it's little annoying.

When I use bottombar for navigation across other pages with some transition, bottombar is jumping and I don't know why.

https://youtu.be/ZlqmFXDWlc8

**Comment by rhanb** [comment]
Hi @b4rtt ,

Unfortunately I can't reproduce the issue with a simple `ScrollView`. Could you provide a `github` repo please? Thanks 👍

**Comment by b4rtt** [comment]
Hi @rhanb,
thank you for you fast response! ;)

My repo is here https://github.com/b4rtt/bouncing_bar

**Comment by rhanb** [comment]
@b4rtt ,

So I manage to reproduce the issue on `android`. It comes from the animation from your `routerExtensions` in your `tabs` component. You added this:

```typescript
 this.routerExtensions.navigate(["/tickets"], {
          clearHistory: true,
          transition: {
          name: "slideTop"
    }
});
```
which will animate your view when navigating between views, but since you choose the animation `slideTop` it will produce this `bouncing` issue. You should use the animation `slideLeft` or `slideRight`

Cheers from france 🇫🇷

**Comment by b4rtt** [comment]
@rhanb Thank you for help.
I realised that it's causing ActionBar flat="true" :-O


Cheers from Czechia 🇨🇿
