### ISSUE TITLE
[Question] : How to handle navigation?

### ISSUE THREAD

**Issue by vahidvdn** [rhanb/nativescript-bottombar#81]
Thanks for this awesome library. I have a question. How can I handle routing in a proper way? (Something like instagram tab bar). Any idea?
That's become very complicated using `page-router-outlet`.

**Comment by vahidvdn** [comment]
@rhanb Thanks for the reply.

But this a very basic implementation. Imagine the following scenario:
You are in the first tab (First route) , you scroll down in your first tab (let's say you have a listview), Then you go through the second tab (second route).

Now if you press back button, because of history in routes, you can see the **scroll position** in first tab. But if you tap the first tab (not back button) , because it will be considered as a new route, you can't see the scroll position.

Another challenge is this, if you go through the tabs multiple times, you will have multiple back and forward, which is not necessary. (As I mentioned, instagram's tab bar is a very good example)

And the  last problem is child routes into each tab. Any idea?

**Comment by rhanb** [comment]
@vahidvdn 

What you can do, to avoid losing the scroll position when clicking on the first tab, is to add a condition on the tab clicked event and verify if it was the previous tab clicked and call `back` instead of `navigate`. 

The issue in this solution is the case where you have at least three tabs and the user navigate to tab 1, scroll down, navigate to tab 2 and then tab 3. If he clicked on tab 1 again calling the function `back` won't work since it's not the last route in history.

The best solution I see would be to not save the history when navigating between tabs and save the offset and then call `scrollToVerticalOffset` when navigating back to a tab. On a UX perspective you shouldn't allow the user to navigate back to a different tab using the back button. 
Also since you won't save the navigation history between tabs it means that you will lose the navigation
history when changing tab, maybe when navigating between tabs you could save the current history of that tab and reassign it if the user navigate back to it.

If you use Ngrx you could use the Store to save those offsets.

For the child routes what is the issue? just place a `router-outlet`

**Comment by rhanb** [comment]
This issue could be avoided if it was possible to define multiple `outlets` and `page-router-outlet` to have splitted history.

**Comment by rhanb** [comment]
Hint: https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/directives/tab-view.ts#L58

**Comment by vahidvdn** [comment]
Thanks @rhanb 
First of all, about your notice:

> The best solution I see would be to not save the history when navigating between tabs and save the offset and then call `scrollToVerticalOffset` when navigating back to a tab

I think we will confront with some performance issues by this solution. It can't be really fast. And from perspective of UX about the ability to tapping back button on Tab View in order to navigating back, it's really a choice. For example, in ionic1 this was possible to have back button, but in ionic2+ , if you press back button, the app will be closed. Another example is Instgaram that lets user to back. This feature is available in most of real world apps.

There is also one more thing which is well implemented in ionic, is when you go to child route in first tab, if you tap on first tab, it works like a back button.

But about defining multiple `outlets` and `page-router-outlet`. I have already read that link from nativescript.org. NativeScript TabView has the issue as well. That's why I decided to install your plugin. For more detail please see my issue [here](https://github.com/NativeScript/NativeScript/issues/6859).

I will try your last code snippet to see how it works.

**Comment by rhanb** [comment]
Yes it's really opiniated, and the behavior between iOS and Android should actually be different, this [section](https://material.io/design/components/bottom-navigation.html#behavior)  is really interesting.

keep me up to date, thanks

**Comment by vahidvdn** [comment]
Hi @rhanb 
After more investigating about this, I found out this feature works fine with `RadlistView`. See [my demo](https://play.nativescript.org/?template=play-ng&id=shdXlC&_ga=2.187508328.1904510131.1549527818-427704897.1494601158&v=2) in playground.

**Comment by rhanb** [comment]
@vahidvdn that's a great new, good to know!
Thanks for the demo.
