### ISSUE TITLE
MiniTabBar Swift 3 no longer support in XCode 10.2

### ISSUE THREAD

**Issue by LSmint** [rhanb/nativescript-bottombar#86]
Getting following issue after upgrade XCode to 10.2:
Swift 3 mode has been deprecated and will be removed in a later version of Xcode. Please migrate "MiniTabBar" to Swift 4.2 using "Convert > To Current Swift Syntax…" in the Edit menu. (in target 'MiniTabBar')

May i know will this plugin support Swift 4.2~5 in future?

**Comment by rhanb** [comment]
Hello @LSmint ,

This plugin doesnt use the third party library MiniTabBar anymore. It uses the native API UITabBAr.
If you upgrade the plugin to the latest version you wont have this issue anymore but there is some breaking changes since the use of MiniTabBar.
Please follow the README to upgrade.

And install it with the following command:

`tns plugin add nativescript-bottombar@next`

**Comment by LSmint** [comment]
Thank alot! @rhanb 

For Notification, in MiniTabBar we can using BottomBar.setNotification(value, index) to update the bar badge. How it works in UITabBar to update badge dynamically?

**Comment by rhanb** [comment]
@LSmint simply change the value of the `badge` property 

API here https://github.com/rhanb/nativescript-bottombar/blob/master/API_DOCUMENTATION.md#bottombaritem

set badge to `null` to hide it
